fix: Allow users to "reactivate" their Dub subscription
dubinc/dub pull request #1333
Opened 2024-10-07 16:57 UTC by RajuGangitla

Allows users with a canceled subscription to reactivate it through Stripe without needing to create a new subscription. 

Fixes #1331

2024-10-07 16:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dubinc/dub?pullRequest=1333) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dubinc/dub?pullRequest=1333) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dubinc/dub?pullRequest=1333) it.</sub>

2024-10-07 16:57 UTC, RajuGangitla commented
@steven-tey

2024-10-07 19:30 UTC, TWilson023 requested changes

2024-10-07 19:30 UTC, TWilson023 commented on apps/web/app/api/workspaces/[idOrSlug]/billing/upgrade/route.ts
> +      ...(workspace.stripeId ? { customer: workspace.stripeId } : { customer_email: session.user.email }),
With this change, when I attempt to upgrade a workspace that doesn't have an active subscription but does have a `stripeId`, I get the following error:
```
StripeInvalidRequestError: Tax ID collection requires updating business name on the customer. To enable tax ID collection for an existing customer, please set `customer_update[name]` to `auto`
```

2024-10-07 19:48 UTC, RajuGangitla commented on apps/web/app/api/workspaces/[idOrSlug]/billing/upgrade/route.ts
> +      ...(workspace.stripeId ? { customer: workspace.stripeId } : { customer_email: session.user.email }),
@TWilson023 i pushed that latest code

2024-10-07 20:02 UTC, TWilson023 approved these changes

2024-10-07 20:25 UTC, steven-tey commented
@RajuGangitla thanks for the PR! Can you please sign the [CLA](https://github.com/dubinc/dub/pull/1333#issuecomment-2397442472) so we can merge the PR?

2024-10-07 20:53 UTC, steven-tey approved these changes

2024-10-08 03:24 UTC, RajuGangitla commented
@steven-tey how can i sign

2024-10-08 17:53 UTC, merged

2024-10-08 17:53 UTC, steven-tey commented
Thank you @RajuGangitla!