added dockerfile for deploying app on container
dubinc/dub pull request #391
Opened 2023-09-24 06:51 UTC by captain-Akshay

Issue #378

This commit includes a Dockerfile and a Docker Compose file to enhance the deployment of the app on a local setup.

However, there is still an issue with containerizing Next.js version 13.4.20-canary.31. To learn more and if you encounter a related issue, please visit https://github.com/vercel/next.js/issues?q=docker+.

I've also added a Docker Compose file with a MySQL server for communication between the containers and made a few minor changes to improve the development experience.

2023-10-09 05:33 UTC, Ashutosh-Malve approved these changes

2023-10-09 05:34 UTC, Ashutosh-Malve approved these changes

2023-10-12 03:50 UTC, steven-tey commented
@captain-Akshay we recently refactored the codebase to a [monorepo via Turborepo](https://dub.co/blog/turborepo-migration) – can we refactor this PR please?

2023-10-12 18:54 UTC, captain-Akshay commented
> @captain-Akshay we recently refactored the codebase to a [monorepo via Turborepo](https://dub.co/blog/turborepo-migration) – can we refactor this PR please?

sure let me take a look

2023-10-24 06:10 UTC, mcnaveen commented on Dockerfile
> +RUN yarn
Running `yarn` works. But I suggest using `yarn install` instead. Much more clear for beginners

2023-12-22 18:04 UTC, skushagra9 commented
If this issue is not solved ,please assign it to me

2023-12-26 10:02 UTC, captain-Akshay commented
apologies for the delay i was busy with some intern work i will finish it up by today!

2024-02-14 00:14 UTC, steven-tey requested changes

2024-02-14 00:14 UTC, steven-tey commented on .env.example
don't think this change is required

2024-02-15 18:11 UTC, Nasir1999 commented
@captain-Akshay any update? ☺

2024-02-22 20:23 UTC, juliomfreitas commented
Finishing this PR would be great for the community. thank you all guys!!!

2024-02-23 08:06 UTC, captain-Akshay commented
Sorry I'm currently busy with something else, you can gladly take this one

2024-02-23 08:06 UTC, closed without merging

2024-03-01 12:04 UTC, fredygerman commented
i see the issue has been closed, has it been merged and is it done?

2025-09-13 16:55 UTC, gabriel-vanca commented
Why was this issue closed? It doesn't seem to have been solved.

2025-12-09 02:28 UTC, jsilvermist commented
I see this PR is still referenced on the [Self-hosting documentation](https://dub.co/docs/self-hosting#step-3%3A-set-up-upstash-redis-database:~:text=Also%2C%20Docker%20is%20currently%20not%20supported%2C%20but%20we%20have%20a%20few%20open%20issues%20and%20PRs%20for%20it.), and would really like this as it's the ideal way to deploy this on my setup, has this been abandoned permanently?