Linkify comments
dubinc/dub pull request #504
Opened 2023-12-17 12:44 UTC by aakash2330

Hyperlink Links in Comments #431

Turn inks within comments clickable

2023-12-17 13:33 UTC, tuffz commented on apps/web/ui/links/linkify-comments.tsx
> +        return <a href={part} key={index} target="_blank" rel="noopener noreferrer" className="hover:underline">{part}</a>;
I would also recommend adding a "nofollow" to the `rel` to avoid link spammers.

2023-12-17 22:14 UTC, unrenamed requested changes
Hey @aakash2330, excited to help with your PR code review!

1) Thinking about making the `<LinkifyText />` component even more modular by moving it to the `packages/ui` module. What do you think? Also, we can tweak the filename to match the component name, maybe something like `linkify-text`.

2) Noticed the #431 issue author mentioned an ideal scenario: allowing URLs without protocols to transform into hyperlinks. 

   > ideally not even requiring entering https:// but open to having that if it makes this easier

    Currently, it seems to support only `http(s)` protocols. Any challenges with this? Maybe check out existing solutions like [linkify.js.org](https://linkify.js.org/)? Let me know your thoughts! 😊

2023-12-18 07:05 UTC, aakash2330 commented
Hey @tuffz @unrenamed thanks for reviewing my pr . 

1 . Added the "nofollow" to the rel attribute as suggested by @tuffz .
2 . Tweaked the filename to match the component name (linkify-comments) and moved it to packages/ui module .
3. Want to get up a heads up from the maintainers before including a third party library that's why I didn't include it in the first place .

2023-12-19 03:19 UTC, steven-tey commented
Thanks a lot for the PR @aakash2330 + feedback from @tuffz & @unrenamed 🙏 

re: `linkifyjs` – it looks lightweight enough, let's use it 😄 (and rely on @socketdev for 3rd party deps security 🔒)

2023-12-19 11:26 UTC, aakash2330 commented
@steven-tey added linkifyjs to support more URL protocols as well as allowing URLs without protocols to transform into hyperlinks.

2023-12-21 03:51 UTC, steven-tey commented
Great work on this PR @aakash2330 – also shoutout to @unrenamed for the linkify tip as well!

Will be merging this now – also updated our [changelog](https://dub.co/changelog/link-comments) & [help docs](https://dub.co/help/article/how-to-create-link#link-comments) to include this too :)

2023-12-21 03:55 UTC, merged