ENG-139 [FEAT]: Github OAuth for Dub
dubinc/dub pull request #561
Opened 2024-01-18 07:06 UTC by versecafe

## Added GitHub OAuth

Related Issue https://github.com/dubinc/dub/issues/538

### Register Screen
<img width="1381" alt="image" src="https://github.com/dubinc/dub/assets/147033096/fac955fd-a34f-4fef-b267-8c3c7fb05c6c">

### Logged In
<img width="1381" alt="image" src="https://github.com/dubinc/dub/assets/147033096/9d1c32eb-adbb-4966-8137-d97ce7b3297f">

> Also added to the log in screen and the env vars needed are in .env.example along with links to next-auth docs for setup.

2024-01-18 20:17 UTC, versecafe commented
Closes https://github.com/dubinc/dub/issues/538

2024-01-29 14:36 UTC, subh-cs commented on apps/web/lib/auth/options.ts
> +        console.log("github user!");
```suggestion
```

2024-01-29 14:38 UTC, subh-cs requested changes
Great stuff @versecafe  🚀

2024-02-04 05:20 UTC, steven-tey approved these changes

2024-02-04 05:21 UTC, steven-tey commented
Incredible work on this PR, thank you so much @versecafe! 🙏

2024-02-04 05:21 UTC, merged