API Changes
dubinc/dub pull request #592
Opened 2024-01-30 17:14 UTC by devkiran

2024-02-05 15:28 UTC, versecafe commented
@devkiran Would moving to drizzle make sense if already adding zod wrappers? fix prismas performance issues and [dirzzle-zod](https://orm.drizzle.team/docs/zod) makes fusing the two to generate type validation from db models easier

2024-03-02 05:19 UTC, steven-tey requested changes

2024-03-02 05:19 UTC, steven-tey commented on apps/docs/api-reference/errors.mdx
Can we add the status codes for each of these responses here? E.g. 403, 404, 400, etc.

2024-03-02 05:19 UTC, steven-tey commented on apps/web/app/api/analytics/[endpoint]/route.ts
this looks great – can we get this added to `/api/analytics/edge/[endpoint]/route.ts` as well?

2024-03-02 05:19 UTC, steven-tey commented on apps/web/app/api/cron/links/event/route.ts
Why do we need to include `excludeRoot` here if it's an optional param?

2024-03-02 05:19 UTC, steven-tey commented on apps/web/app/api/links/route.ts
> -    const { link, error, status } = await processLink({
what happened to `status`? should we remove it and fully rely on `code`?

2024-03-02 05:19 UTC, steven-tey commented on apps/web/app/api/og/analytics/route.tsx
> +    excludeRoot: false
same question about `excludeRoot` – why do we need to define it? can it just be left undefined

2024-03-02 11:27 UTC, devkiran commented on apps/docs/api-reference/errors.mdx
Yup, I'll add status codes.

2024-03-02 11:36 UTC, devkiran commented on apps/web/app/api/analytics/[endpoint]/route.ts
Sure.

2024-03-02 15:11 UTC, devkiran commented on apps/web/app/api/cron/links/event/route.ts
Good catch, can fix it with some tweak in zod schema.

2024-03-02 15:12 UTC, devkiran commented on apps/web/app/api/og/analytics/route.tsx
> +    excludeRoot: false
Yup, it can left undefined

2024-03-02 15:14 UTC, devkiran commented on apps/web/app/api/links/route.ts
> -    const { link, error, status } = await processLink({
`status` was replaced with error `code`, no longer needed. I think we can safely remove `status`.

2024-03-06 16:47 UTC, steven-tey approved these changes

2024-03-06 17:19 UTC, merged