ENG-295: Add custom context menu for copying nav logo
dubinc/dub pull request #823
Opened 2024-04-27 02:46 UTC by TWilson023

Adds a `CopiableLogo` component (not in love with the name) that has a custom context menu for copying the logo SVG:

<img width="283" alt="Screenshot 2024-04-26 at 10 45 31 PM (2)" src="https://github.com/dubinc/dub/assets/2547408/209c2582-63c2-4f4b-94b5-09ee00fa268a">

2024-04-27 02:47 UTC, TWilson023 commented on packages/ui/src/copiable-logo.tsx
> +const logoSvg = `<svg width="834" height="236" viewBox="0 0 834 236" fill="none" xmlns="http://www.w3.org/2000/svg">
Is there a better way to pull this logo SVG for copying it without waiting on a `fetch`?

2024-04-27 02:47 UTC, TWilson023 commented on packages/ui/src/copiable-logo.tsx
> +export default function CopiableLogo({ className }: { className?: string }) {
Don't love this name...

2024-04-28 20:31 UTC, steven-tey requested changes
Requested some changes on Slack 🙏

2024-05-01 11:58 UTC, steven-tey approved these changes

2024-05-02 14:25 UTC, merged